name: Vinted Scanner

on:
  schedule:
    # Run every hour at minute 0
    - cron: '0 * * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        pip install requests
        
    - name: Run scanner
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
        GIST_ID: ${{ secrets.GIST_ID }}
        VINTED_QUERIES: ${{ secrets.VINTED_QUERIES }}
      run: |
        python vinted_scanner_github.py
